ZCS-4713:Upgrade guava jar
Zimbra/zm-clam-scanner-store pull request #1
Opened 2018-04-03 11:10 UTC by swapnilpingle89

Upgrade guava jar to the latest version(23)

2018-04-03 11:10 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/Zimbra/zm-clam-scanner-store?pullRequest=1) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/Zimbra/zm-clam-scanner-store?pullRequest=1) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/Zimbra/zm-clam-scanner-store?pullRequest=1) it.</sub>

2018-04-04 06:30 UTC, rupalid approved these changes

2018-04-04 06:30 UTC, chinmay15 approved these changes

2018-04-04 09:21 UTC, fatkudu requested changes
Worth deleting .classpath / .project and adding those to .gitignore?  .classpath has what will become stale references to guava in it.

2018-06-15 06:19 UTC, merged